### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by skyl** [hhanh00/zwallet#23]
Hi @hhanh00 ! Great work with zwallet/ywallet! You've been huge in keeping a reliable lightwallet going strong through the network upgrade and with a fast sync through spam attacks. Ywallet rocks!

Since I rely on your work, I'd like to understand it better and contribute to it, possibly depend on it. Unfortunately I have no experience with Dart and don't yet know exactly how to spin up development versions locally.

I started to try to use BUILD.md and sort of got somewhere. I left some throwaway notes in this branch:

https://github.com/hhanh00/zwallet/compare/main...free2z:zwallet:trying-to-build

I learned some things and I'm going to start over at `main` and try again. I might be able to figure it out and perhaps write a guide or two that will solve this present issue. "How to Iaunch a local desktop version of YWallet on X", "How to run YWallet on an {iOS|Android} emulator". Let me know if I might have just missed something like this or if you have any ideas/direction for what you'd like to see.

**Comment by hhanh00** [comment]
Thanks,
What is the issue?

**Comment by hhanh00** [comment]
Btw, if you are looking to integrate as a server, there is no need to bother with the Dart/Flutter code. You can build the warp sync wallet engine as a standalone RPC/REST server.
It is just pure rust.

**Comment by skyl** [comment]
> Thanks, What is the issue?

In the big picture, it's that I've spent a couple of hours messing around with it and looking at BUILD.md and not yet getting to the point where I can run anything.

To start, I take BUILD.md as a guide and try to go through step-by-step

```
hhanh00/zwallet|main 
⇒  keytool -genkey -v -keystore $ZWALLET/docker/zwallet.jks -keyalg RSA -keysize 2048 -validity 10000 -alias zwallet
Enter keystore password:  
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
java.io.IOException: Keystore was tampered with, or password was incorrect
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
        at java.base/java.security.KeyStore.load(Unknown Source)
        at java.base/sun.security.tools.keytool.Main.doCommands(Unknown Source)
        at java.base/sun.security.tools.keytool.Main.run(Unknown Source)
        at java.base/sun.security.tools.keytool.Main.main(Unknown Source)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        ... 6 more
```

I notice that a file at [$ZWALLET/docker/zwallet.jks](https://github.com/hhanh00/zwallet/blob/main/docker/zwallet.jks) already exists. So, maybe I should try a different location?

```
⇒  keytool -genkey -v -keystore $ZWALLET/zwallet.jks -keyalg RSA -keysize 2048 -validity 10000 -alias zwallet 
Enter keystore password:  
Re-enter new password: 
What is your first and last name?
  [Unknown]:  
What is the name of your organizational unit?
  [Unknown]:  
What is the name of your organization?
  [Unknown]:  
What is the name of your City or Locality?
  [Unknown]:  
What is the name of your State or Province?
  [Unknown]:  
What is the two-letter country code for this unit?
  [Unknown]:  
Is CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown correct?
  [no]:  yes

Generating 2,048 bit RSA key pair and self-signed certificate (SHA256withRSA) with a validity of 10,000 days
        for: CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=Unknown
[Storing hhanh00/zwallet/zwallet.jks]
```

So, that at least runs. But, I start to wonder if this is something I should really need to do to spin up a local dev version ... let's keep going though ..

> Skip the next section if you want to use my builder image

Okay, let's try that. The first time I ran through this it didn't work because of some version problem I didn't write down. Let's see if that happens again ...

I put my keystore password I just used in `/some/place/jkspwd` ...

```
DOCKER_BUILDKIT=1 docker build -t zwallet -f docker/Dockerfile --secret id=pwd,src=/some/place/jkspwd .
```

Oh, now I remember the version problem:

```
[+] Building 131.7s (12/13)                                                          
 => [internal] load build definition from Dockerfile                            0.1s
 => => transferring dockerfile: 466B                                            0.0s
 => [internal] load .dockerignore                                               0.0s
 => => transferring context: 34B                                                0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                    2.7s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab  0.0s
 => [internal] load metadata for docker.io/hhanh00/zwallet_builder:latest       1.3s
 => [internal] load metadata for docker.io/library/alpine:latest                1.2s
 => [internal] load build context                                               0.1s
 => => transferring context: 37.35kB                                            0.1s
 => CACHED [builder 1/3] FROM docker.io/hhanh00/zwallet_builder@sha256:1b53be5  0.0s
 => [stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:686d8c9dfa6f3ccf  0.0s 
 => CACHED [stage-1 2/3] WORKDIR /root                                          0.0s 
 => [builder 2/3] COPY . /zwallet                                               0.4s 
 => ERROR [builder 3/3] RUN --mount=type=secret,id=pwd cd /zwallet && ./conf  125.2s 
------                                                                               
 > [builder 3/3] RUN --mount=type=secret,id=pwd cd /zwallet && ./configure.sh zcash && ./build.sh:
#10 2.660    Woah! You appear to be trying to run flutter as root.
#10 2.660    We strongly recommend running the flutter tool without superuser privileges.
#10 2.660   /
#10 2.660 📎
#10 28.19 ╔════════════════════════════════════════════════════════════════════════════╗
#10 28.19 ║ A new version of Flutter is available!                                     ║
#10 28.19 ║                                                                            ║
#10 28.19 ║ To update to the latest version, run "flutter upgrade".                    ║
#10 28.19 ╚════════════════════════════════════════════════════════════════════════════╝
#10 28.19 
#10 30.27 
#10 30.27   ╔════════════════════════════════════════════════════════════════════════════╗
#10 30.27   ║                 Welcome to Flutter! - https://flutter.dev                  ║
#10 30.27   ║                                                                            ║
#10 30.27   ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
#10 30.27   ║ statistics and basic crash reports. This data is used to help improve      ║
#10 30.27   ║ Flutter tools over time.                                                   ║
#10 30.27   ║                                                                            ║
#10 30.27   ║ Flutter tool analytics are not sent on the very first run. To disable      ║
#10 30.27   ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
#10 30.27   ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
#10 30.27   ║ event will be sent, and then no further information will be sent by the    ║
#10 30.27   ║ Flutter tool.                                                              ║
#10 30.27   ║                                                                            ║
#10 30.27   ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
#10 30.27   ║ Note: The Google Privacy Policy describes how data is handled in this      ║
#10 30.27   ║ service.                                                                   ║
#10 30.27   ║                                                                            ║
#10 30.27   ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
#10 30.27   ║ crash reports to Google.                                                   ║
#10 30.27   ║                                                                            ║
#10 30.27   ║ Read about data we send with crash reports:                                ║
#10 30.27   ║ https://flutter.dev/docs/reference/crash-reporting                         ║
#10 30.27   ║                                                                            ║
#10 30.27   ║ See Google's privacy policy:                                               ║
#10 30.27   ║ https://policies.google.com/privacy                                        ║
#10 30.27   ╚════════════════════════════════════════════════════════════════════════════╝
#10 30.27 
#10 30.35 Running "flutter pub get" in flutter_tools...                       6.3s
#10 36.94 Running "flutter pub get" in zwallet...                         
#10 40.17 The current Dart SDK version is 2.16.1.
#10 40.17 
#10 40.17 Because animated_text_kit 4.2.2 requires SDK version >=2.17.0 <3.0.0 and no versions of animated_text_kit match >4.2.2 <5.0.0, animated_text_kit ^4.2.2 is forbidden.
#10 40.17 So, because ZYWallet depends on animated_text_kit ^4.2.2, version solving failed.
#10 40.53 pub get failed (1; So, because ZYWallet depends on animated_text_kit ^4.2.2, version solving failed.)
#10 40.61    Woah! You appear to be trying to run flutter as root.
#10 40.61    We strongly recommend running the flutter tool without superuser privileges.
#10 40.61   /
#10 40.61 📎
#10 42.31 /flutter/packages/flutter/pubspec.yaml has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
#10 42.43 pub finished with exit code 65
#10 42.73    Woah! You appear to be trying to run flutter as root.
#10 42.73    We strongly recommend running the flutter tool without superuser privileges.
#10 42.73   /
#10 42.73 📎
#10 44.40 /flutter/packages/flutter/pubspec.yaml has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
#10 44.52 pub finished with exit code 65
#10 44.82    Woah! You appear to be trying to run flutter as root.
#10 44.82    We strongly recommend running the flutter tool without superuser privileges.
#10 44.82   /
#10 44.82 📎
#10 46.45 /flutter/packages/flutter/pubspec.yaml has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
#10 47.56 pub finished with exit code 65
#10 47.80    Woah! You appear to be trying to run flutter as root.
#10 47.80    We strongly recommend running the flutter tool without superuser privileges.
#10 47.80   /
#10 47.80 📎
#10 48.85 Running "flutter pub get" in warp_api_ffi...                        8.9s
#10 58.06    Woah! You appear to be trying to run flutter as root.
#10 58.06    We strongly recommend running the flutter tool without superuser privileges.
#10 58.06   /
#10 58.06 📎
#10 71.65 [INFO] Generating build script...
#10 72.27 [INFO] Generating build script completed, took 644ms
#10 72.27 
#10 72.39 [INFO] Precompiling build script......
#10 82.20 [INFO] Precompiling build script... completed, took 9.8s
#10 82.20 
#10 83.10 [INFO] Initializing inputs
#10 83.88 [INFO] Building new asset graph...
#10 85.34 [INFO] Building new asset graph completed, took 1.5s
#10 85.34 
#10 85.34 [INFO] Checking for unexpected pre-existing outputs....
#10 85.35 [INFO] Checking for unexpected pre-existing outputs. completed, took 3ms
#10 85.35 
#10 85.37 [INFO] Running build...
#10 85.44 [INFO] Generating SDK summary...
#10 91.14 [INFO] 5.8s elapsed, 0/3 actions completed.
#10 91.17 [INFO] Generating SDK summary completed, took 5.7s
#10 91.17 
#10 92.04 [WARNING] json_serializable:json_serializable on lib/types.dart:
#10 92.04 Your current `analyzer` version may not fully support your current SDK version.
#10 92.04 
#10 92.04 Analyzer language version: 2.15.0
#10 92.04 SDK language version: 2.16.0
#10 92.04 
#10 92.04 Please update to the latest `analyzer` version (4.2.0) by running
#10 92.04 `flutter packages upgrade`.
#10 92.04 
#10 92.04 If you are not getting the latest version by running the above command, you
#10 92.04 can try adding a constraint like the following to your pubspec to start
#10 92.04 diagnosing why you can't get the latest version:
#10 92.04 
#10 92.04 dev_dependencies:
#10 92.04   analyzer: ^4.2.0 
#10 92.04 
#10 92.45 [INFO] Running build completed, took 7.1s
#10 92.45 
#10 92.45 [INFO] Caching finalized dependency graph...
#10 92.50 [INFO] Caching finalized dependency graph completed, took 49ms
#10 92.50 
#10 92.52 [INFO] Succeeded after 7.2s with 2 outputs (7 actions)
#10 92.52 
#10 107.8 [cargo-make] INFO - cargo make 0.35.9
#10 118.1 [cargo-make] WARN - Found unknown key: tasks.?.build.mac.?.description in file: ./Makefile.toml
#10 118.1 [cargo-make] WARN - Found unknown key: tasks.?.build.mac.?.category in file: ./Makefile.toml
#10 118.6 [cargo-make] INFO - Build File: Makefile.toml
#10 118.6 [cargo-make] INFO - Task: default
#10 118.6 [cargo-make] INFO - Profile: release
#10 118.6 [cargo-make] INFO - Running Task: legacy-migration
#10 118.6 [cargo-make] INFO - Running Task: workspace
#10 118.6 [cargo-make] INFO - Build Done in 10.83 seconds.
#10 118.6    Woah! You appear to be trying to run flutter as root.
#10 118.6    We strongly recommend running the flutter tool without superuser privileges.
#10 118.6   /
#10 118.6 📎
#10 120.1 Running "flutter pub get" in zwallet...                         
#10 124.4 The current Dart SDK version is 2.16.1.
#10 124.4 
#10 124.4 Because animated_text_kit 4.2.2 requires SDK version >=2.17.0 <3.0.0 and no versions of animated_text_kit match >4.2.2 <5.0.0, animated_text_kit ^4.2.2 is forbidden.
#10 124.4 So, because ZYWallet depends on animated_text_kit ^4.2.2, version solving failed.
#10 124.9 pub get failed (1; So, because ZYWallet depends on animated_text_kit ^4.2.2, version solving failed.)
------
executor failed running [/bin/sh -c cd /zwallet && ./configure.sh zcash && ./build.sh]: exit code: 1
```

I'll try to switch the builder image to a locally built one ...

In the grand scheme of things, I'm a Python/Django nub who really enjoys hand-holdy guides and super impressive developer ergonomics and initial impressions, long walks on the beach. So, I'm hoping to write/read such a guide for how to get started hacking on ywallet.

**Comment by skyl** [comment]
With the local version `FROM zwallet_builder AS builder`:

```
⇒  DOCKER_BUILDKIT=1 docker build -t zwallet -f docker/Dockerfile --secret id=pwd,src=/Users/skyl/jkspwd .
[+] Building 39.4s (12/13)                                                                             
 => [internal] load build definition from Dockerfile                                              0.0s
 => => transferring dockerfile: 500B                                                              0.0s
 => [internal] load .dockerignore                                                                 0.0s
 => => transferring context: 34B                                                                  0.0s
 => resolve image config for docker.io/docker/dockerfile:1.2                                      0.6s
 => CACHED docker-image://docker.io/docker/dockerfile:1.2@sha256:e2a8561e419ab1ba6b2fe6cbdf49fd9  0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                  1.2s
 => [internal] load metadata for docker.io/library/zwallet_builder:latest                         0.0s
 => [internal] load build context                                                                 0.1s
 => => transferring context: 1.50MB                                                               0.1s
 => CACHED [builder 1/3] FROM docker.io/library/zwallet_builder                                   0.0s
 => [stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84e  0.0s
 => CACHED [stage-1 2/3] WORKDIR /root                                                            0.0s
 => [builder 2/3] COPY . /zwallet                                                                 0.1s
 => ERROR [builder 3/3] RUN --mount=type=secret,id=pwd cd /zwallet && ./configure.sh zcash && .  36.8s
------                                                                                                 
 > [builder 3/3] RUN --mount=type=secret,id=pwd cd /zwallet && ./configure.sh zcash && ./build.sh:     
#12 0.438    Woah! You appear to be trying to run flutter as root.                                     
#12 0.438    We strongly recommend running the flutter tool without superuser privileges.              
#12 0.438   /                                                                                          
#12 0.438 📎                                                                                           
#12 0.470 fatal: unsafe repository ('/root/flutter' is owned by someone else)
#12 0.470 To add an exception for this directory, call:
#12 0.470 
#12 0.470       git config --global --add safe.directory /root/flutter
#12 0.517 Building flutter tool...
#12 23.88 
#12 23.88   ╔════════════════════════════════════════════════════════════════════════════╗
#12 23.88   ║                 Welcome to Flutter! - https://flutter.dev                  ║
#12 23.88   ║                                                                            ║
#12 23.88   ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
#12 23.88   ║ statistics and basic crash reports. This data is used to help improve      ║
#12 23.88   ║ Flutter tools over time.                                                   ║
#12 23.88   ║                                                                            ║
#12 23.88   ║ Flutter tool analytics are not sent on the very first run. To disable      ║
#12 23.88   ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
#12 23.88   ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
#12 23.88   ║ event will be sent, and then no further information will be sent by the    ║
#12 23.88   ║ Flutter tool.                                                              ║
#12 23.88   ║                                                                            ║
#12 23.88   ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
#12 23.88   ║ Note: The Google Privacy Policy describes how data is handled in this      ║
#12 23.88   ║ service.                                                                   ║
#12 23.88   ║                                                                            ║
#12 23.88   ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
#12 23.88   ║ crash reports to Google.                                                   ║
#12 23.88   ║                                                                            ║
#12 23.88   ║ Read about data we send with crash reports:                                ║
#12 23.88   ║ https://flutter.dev/docs/reference/crash-reporting                         ║
#12 23.88   ║                                                                            ║
#12 23.88   ║ See Google's privacy policy:                                               ║
#12 23.88   ║ https://policies.google.com/privacy                                        ║
#12 23.88   ╚════════════════════════════════════════════════════════════════════════════╝
#12 23.88 
#12 24.30 Running "flutter pub get" in zwallet...                         
#12 27.17 The current Flutter SDK version is 0.0.0-unknown.
#12 27.17 
#12 27.17 Because ZYWallet depends on audioplayers >=0.13.7 which requires Flutter SDK version >=1.10.0, version solving failed.
#12 27.33 pub get failed (1; Because ZYWallet depends on audioplayers >=0.13.7 which requires Flutter SDK version >=1.10.0, version solving failed.)
#12 27.39    Woah! You appear to be trying to run flutter as root.
#12 27.39    We strongly recommend running the flutter tool without superuser privileges.
#12 27.39   /
#12 27.39 📎
#12 27.40 fatal: unsafe repository ('/root/flutter' is owned by someone else)
#12 27.40 To add an exception for this directory, call:
#12 27.40 
#12 27.40       git config --global --add safe.directory /root/flutter
#12 28.87 The pubspec_overrides.yaml file has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
#12 30.04 pub finished with exit code 65
#12 30.15    Woah! You appear to be trying to run flutter as root.
#12 30.15    We strongly recommend running the flutter tool without superuser privileges.
#12 30.15   /
#12 30.15 📎
#12 30.15 fatal: unsafe repository ('/root/flutter' is owned by someone else)
#12 30.15 To add an exception for this directory, call:
#12 30.15 
#12 30.15       git config --global --add safe.directory /root/flutter
#12 32.21 The pubspec_overrides.yaml file has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
#12 32.32 pub finished with exit code 65
#12 32.38    Woah! You appear to be trying to run flutter as root.
#12 32.38    We strongly recommend running the flutter tool without superuser privileges.
#12 32.38   /
#12 32.38 📎
#12 32.38 fatal: unsafe repository ('/root/flutter' is owned by someone else)
#12 32.38 To add an exception for this directory, call:
#12 32.38 
#12 32.38       git config --global --add safe.directory /root/flutter
#12 33.70 The pubspec_overrides.yaml file has changed since the pubspec.lock file was generated, please run "flutter pub get" again.
#12 33.82 pub finished with exit code 65
#12 33.89    Woah! You appear to be trying to run flutter as root.
#12 33.89    We strongly recommend running the flutter tool without superuser privileges.
#12 33.89   /
#12 33.89 📎
#12 33.89 fatal: unsafe repository ('/root/flutter' is owned by someone else)
#12 33.89 To add an exception for this directory, call:
#12 33.89 
#12 33.89       git config --global --add safe.directory /root/flutter
#12 34.89 Running "flutter pub get" in warp_api_ffi...                    
#12 35.31 The current Flutter SDK version is 0.0.0-unknown.
#12 35.31 
#12 35.31 Because warp_api requires Flutter SDK version >=1.20.0, version solving failed.
#12 35.42 pub get failed (1; Because warp_api requires Flutter SDK version >=1.20.0, version solving failed.)
#12 35.48    Woah! You appear to be trying to run flutter as root.
#12 35.48    We strongly recommend running the flutter tool without superuser privileges.
#12 35.48   /
#12 35.48 📎
#12 35.48 fatal: unsafe repository ('/root/flutter' is owned by someone else)
#12 35.48 To add an exception for this directory, call:
#12 35.48 
#12 35.48       git config --global --add safe.directory /root/flutter
#12 36.65 No .dart_tool/package_config.json file found, please run "flutter pub get".
#12 36.65 
#12 36.65 Starting with Dart 2.7, the package_config.json file configures resolution of package import URIs; run "flutter pub get" to generate it.
#12 36.77 pub finished with exit code 65
------
executor failed running [/bin/sh -c cd /zwallet && ./configure.sh zcash && ./build.sh]: exit code: 65
```

So, just to flail at this error message a little bit, I add

```
RUN git config --global --add safe.directory /root/flutter
```

before [this line](https://github.com/hhanh00/zwallet/blob/0e7a26c63a6d2b9b12a602e41990e27fc0bc0f2c/docker/Dockerfile#L10)

What happens next? It does miraculously get farther ... I'm wondering where I'm going exactly ... BUILD.md seems to suggest that I'll have an `apk` in a finished image that I can copy out. But, **how will I get the iOS version? How will I run the apk on a local emulator? How can I build the native version for my OS? What's the easiest way to get the UI source to hot-reload into something so I can hack on it?** `Woah! You appear to be trying to run flutter as root.` ... I have time to think about some of these things as docker runs a lot farther this time. I'll report back what it says and if I get any apks out the other side.

**Comment by skyl** [comment]
Do you develop with `flutter run`?

**Comment by hhanh00** [comment]
I think the easiest way to troubleshoot is to check out what GitHub CI does.
https://github.com/hhanh00/zwallet/blob/main/.github/workflows/build.yml

From what I can glance from your logs, you may be using an old Dockerfile

**Comment by skyl** [comment]
trying `flutter run` and choosing iOS

```
Launching lib/main.dart on iPhone 12 in debug mode...
Upgrading Info.plist
Running pod install...                                                    25.9s
Running Xcode build...                                                  
Xcode build done.                                           15.4s
Failed to build iOS app
Error output from Xcode build:
↳
    2022-07-07 00:19:33.347 xcodebuild[14032:3916838] Requested but did
    not find extension point with identifier
    Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in
    com.apple.dt.IDEWatchSupportCore
    2022-07-07 00:19:33.348 xcodebuild[14032:3916838] Requested but did
    not find extension point with identifier
    Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for
    extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS
    of plug-in com.apple.dt.IDEWatchSupportCore
    xcodebuild: error: Unable to find a destination matching the
    provided destination specifier:
                { id:FEED2DFA-90F5-4D84-80BF-3B278184FE74 }

        Ineligible destinations for the "Runner" scheme:
                { platform:iOS,
                id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any
                iOS Device }
                { platform:iOS Simulator,
                id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:pla
                ceholder, name:Any iOS Simulator Device }

Could not build the application for the simulator.
Error launching application on iPhone 12.
```

**Comment by skyl** [comment]
> From what I can glance from your logs, you may be using an old Dockerfile

I'm using the one(s) in the main branch of this repo?

**Comment by hhanh00** [comment]
Try Dockerfile-dev
